Implement setting, getting, and autogeneration of task estimations
quayside-app/quayside pull request #21
Opened 2024-04-06 02:15 UTC by crazykyler005

2024-04-10 18:46 UTC, erwilliams64 commented
I just tried to run this today and it didn't work for some reason! hmmmm, will investigate more. cc @crazykyler005

2024-04-17 03:06 UTC, erwilliams64 commented
Pressing enter when the duration field is selected will delete the task!

2024-04-17 17:24 UTC, erwilliams64 commented
Also, I mistook the example duration for the actual duration. We should change this field to look like the other input fields and format it "dd hh mm" or have a tooltip question mark thing next to it.

2024-04-17 18:53 UTC, erwilliams64 commented
Also, durations are required to be input to save a task. These should not be required!

2024-04-18 23:10 UTC, crazykyler005 commented
> Also, I mistook the example duration for the actual duration. We should change this field to look like the other input fields and format it "dd hh mm" or have a tooltip question mark thing next to it.

I think the easiest way to resolve the misunderstanding on the users part would be to either hide the placeholder text until they try to modify a blank duration or make sure to always auto-fill the prompt with 0m if there is no duration and have the placeholder/example text appear if they've manually cleared the textarea

2024-04-18 23:31 UTC, crazykyler005 commented
> Pressing enter when the duration field is selected will delete the task!

had to set the type property for the delete button to "button". It was probably set to "submit" by default
`<button type="button">Whatever</button>`

2024-04-22 02:09 UTC, schromya requested changes

2024-04-22 02:09 UTC, schromya commented on api/views/v1/generatedTasks.py
You don't seem to be parsing the time out correctly in some instances. For example I entered the project idea `learn to code` and printed out the direct response from ChatGPT below. However, all of the tasks listed 0m durations:
```
1. Research different programming languages and choose one to focus on [30 minutes]
   1.1 Explore the characteristics and use cases of popular programming languages
   1.2 Consider personal interests and career goals when selecting a language

2. Learn the basics of the chosen programming language [60 minutes]
   2.1 Study syntax, data types, and basic concepts
   2.2 Practice writing simple programs or scripts

3. Complete online tutorials or courses to deepen understanding [120 minutes]
   3.1 Enroll in an online course or tutorial for the chosen language
   3.2 Follow along with exercises and projects to apply knowledge

4. Build small projects to apply what you have learned [90 minutes]
   4.1 Start with simple projects like a to-do list or calculator
   4.2 Gradually increase the complexity of projects to challenge yourself
  ```

2024-04-22 02:09 UTC, schromya commented on api/views/v1/generatedTasks.py
I also played around with the following prompt and it seemed more likely to return tasks with estimates (although it started returning parenthesis instead of brackets):
```
"content": """You are an assistant for quayside.app, a project management team. 
You are given as input a project or task that a single person or a team 
wants to take on. Divide the task into less than 5 subtasks and list them 
hierarchically in the format where task 1 has subtasks 1.1, 1.2,...
and task 2 has subtasks 2.1, 2.2, 2.3,... and so forth. For each task and subtask, 
provide a time estimation in minutes in brackets with the label "minutes"
Make sure that every task is on one line after the number and has a time estimation. 
NEVER create new paragraphs within a task or subtask.
"""
```
 
Another idea to have more consistent time estimates is to only have ChatGPT estimates for the lowest level of the tree and then sum those estimates to get the duration of the parent tasks.

2024-04-23 01:01 UTC, crazykyler005 commented on api/views/v1/generatedTasks.py
This was intentional. Since the subtasks are the tasks that need to be done to finish the primary task, there should be no reason to account for the generated primary task duration. Also the primary task duration doesn't always equate to the additive value of the subtasks generating.

2024-04-23 01:07 UTC, crazykyler005 commented on api/views/v1/generatedTasks.py
I'd prefer that we remove that duration field for a primary task form entirely and have a separate form for subtasks

2024-04-23 06:17 UTC, crazykyler005 commented on api/views/v1/generatedTasks.py
> Another idea to have more consistent time estimates is to only have ChatGPT estimates for the lowest level of the tree and then sum those estimates to get the duration of the parent tasks.

Changed this so that we now use subtasks to calculate the primary task duration or use the parsed minute value for the primary task if it doesn't have subtask/s

2024-04-24 02:59 UTC, schromya commented on api/views/v1/generatedTasks.py
Root task isn't the sum of child task time estimates.

2024-04-24 20:27 UTC, schromya approved these changes
Looks good to me!

2024-04-24 20:27 UTC, merged