fixed env updater and added error for missing .env
quayside-app/quayside pull request #24
Opened 2024-04-11 00:41 UTC by maximishchuk

- moved check_env code to be called in the rundev command
- made it so that the env updater doesn't read/write blank lines
- script now raises an error and stops the program when a .env file isn't detected

2024-04-11 04:35 UTC, schromya requested changes
+ Still need to raise error instead of `print(f".env file missing variable {check_line}")`
+ Convert everything to camel case (it's our style standard) and run `black app api` to format your code. Run `pylint app/ api/` and see if there's any issues too.
+ Blank lines are still being added to the env_check_file (not really that big of a deal if it's too hard to fix).

2024-04-17 02:49 UTC, crazykyler005 commented on app/management/commands/rundev.py
> +        counter += 1
counter is not being used

2024-04-17 02:49 UTC, crazykyler005 commented on app/management/commands/rundev.py
> +                LINE_EXISTS = True
there is a lot of cleanup that can happen here:
```suggestion
file_dir = os.path.dirname(os.path.realpath('__file__'))
env_file_path = os.path.join(file_dir, ".env")
env_checker_path = os.path.join(file_dir, "env_check_file")

def check_env():
    # checks .env for all the required fields
    # print('Checking Environment Variables...')
    
    if not os.path.exists(env_file_path):
        print("The .env file does not exist, you should create it!")
        exit()
    	
    if not os.path.exists(env_checker_path):
        print('env_check_file not found, creating...')
        
	# w+ gives read and write access to file and creates it if it doesn't exist
    checker_properties = []
        
	# using "with open" ensures that the file gets opened and closed without having to explicitly call f.close()
    with open(os.path.join(env_checker_path, "r+")) as f:
        checker_properties = f.readlines()
    
    for property in checker_properties:
        property.replace(" ","")
        LINE_EXISTS = False
        
		# if is empty
        if not property:
            continue

        env_properties = []
        with open(os.path.join(file_dir,'.env'), "r") as f:
            env_properties = f.readlines()
            
        for env_line in env_properties:
            if env_line.find(property) != -1:
                LINE_EXISTS = True
                break
            
        if LINE_EXISTS == False:
            print(f".env file missing variable {property}")
```

2024-04-17 02:49 UTC, crazykyler005 commented on app/management/commands/rundev.py
> +        check_env()
should we have this return a true or false value and auto-quit if we are missing a known property?

2024-04-17 02:49 UTC, crazykyler005 commented on app/management/commands/rundev.py
> +    env_check_file = open(os.path.join(file_dir,'env_check_file'))
if your opening a file like this make sure you close it or use `with open` to automatically do so

2024-04-17 02:58 UTC, crazykyler005 commented on app/management/commands/rundev.py
> +        counter += 1
also, for future reference, a cleaner way to do this is using enumerate with your for statement:
```
	for count, check_line in enumerate(env_check_file):
```

2024-04-17 23:47 UTC, crazykyler005 commented on app/management/commands/rundev.py
> +                LINE_EXISTS = True
same for the checker_env_update function:
```
def check_env_updater():
    env_properties = []
    with open(env_file_path,'.env') as f:
        for line in f.read().split("\n"):
            env_properties.append(line.split("=")[0].replace(" ",""))
```

2024-05-22 03:44 UTC, schromya requested changes
I'm getting the message `.env file missing manditory MONGO_USERNAME` although MONGO_USERNAME is in my .env

2024-05-22 04:24 UTC, crazykyler005 commented
> I'm getting the message `.env file missing manditory MONGO_USERNAME` although MONGO_USERNAME is in my .env

I'm not able to replicate this issue....

2024-05-29 02:12 UTC, schromya approved these changes
Bug is fixed :D

2024-05-29 02:12 UTC, merged