UI bug fixes
quayside-app/quayside pull request #43
Opened 2024-07-03 04:13 UTC by schromya

* Fixed hidden delete task modal.
* Fixed partially hidden task modal on certain screens.
* Fixed assignees and statuses not working on new tasks.

2024-07-03 05:57 UTC, erwilliams64 commented
Loading the task modal takes a noticeable amount of time now.

2024-07-03 06:02 UTC, erwilliams64 requested changes
Improve task modal load times so they are not noticeable

2024-07-04 20:23 UTC, schromya commented
> Improve task modal load times so they are not noticeable

I think that the relative slowness is due to running it locally. Main currently has fine task load times when I access it through our hosted website but once I pulled it locally, it slows. This may be due to both Mongo and the site being hosted on Google Cloud so interaction between the server and db is quicker which makes it load faster.

Once this branch is merged with main and hosted, the load time should be fine. If not I can fix it then.

2024-07-05 07:16 UTC, erwilliams64 approved these changes

2024-07-05 07:16 UTC, merged